### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BlackIQ** [parsampsh/besanj-frontend#1]
Hi Parsa,

I cloned you app to test it and try to find any issues and things like this. When I started you app, it showed an **error**.

I didn't really read the code yet and wanted to tell you that it has an error.

Regards.
Amir.

![Screenshot from 2022-03-28 17-17-40](https://user-images.githubusercontent.com/55284339/160401624-e6e65de7-b292-4731-81ff-b7bafcb89c87.png)

**Comment by parsampsh** [comment]
Hi dear Amir. It is because you haven't ran the backend application. This app needs the backend accessible at the URL which is determined in `src/Api.js` in a const named `baseUrl`. The backend is written in Django and it is here: https://github.com/parsampsh/besanj-django

**Comment by BlackIQ** [comment]
Hi,

Yes I saw the Django application. Why don't you handle this error?
I mean to show a modal or anything that tell the user that the server is down.
