### ISSUE TITLE
Front-End

### ISSUE THREAD

**Issue by BlackIQ** [parsampsh/besanj-frontend#2]
Hi Parsa,

Your app doesn't seems working well. It has some problems in Navbar I thing. If the nav is going to be like this, so there is no problem but if not, It is a problem.

Regards.
Amir.

![Screenshot from 2022-03-28 17-24-12](https://user-images.githubusercontent.com/55284339/160402585-71dc6d30-bf89-4eeb-a2fe-6aed8d66a4d4.png)
![Screenshot from 2022-03-28 17-22-56](https://user-images.githubusercontent.com/55284339/160402592-9369ad58-5210-413b-990d-e862adfabbbe.png)

**Comment by parsampsh** [comment]
Hi. If you mean about the design and appearance, I haven't designed it. It's just as shit as you can see :)) This project was more about undrestanding the structure of the front end apps. So i didn't pay attention to the design.

**Comment by BlackIQ** [comment]
Hi,

Would you like to have a great front-end with Material Design?
If yes, tell me and I will work on it as soon as possible.

**Comment by parsampsh** [comment]
> Hi,
> 
> Would you like to have a great front-end with Material Design? If yes, tell me and I will work on it as soon as possible.

Why not. If you have free time to do it it's great. I'll give you the commit access to the repo.

**Comment by BlackIQ** [comment]
Tnx. I'll fork it. No access needed.

So, I think we can close the issue.
